baseurl: ""
url:     ""

#----------------------------------------------------------------------
title:  "Portfolio"

avatar: "assets/avatar/example-avatar.webp" #profile picture for portfolio
name:   "Your name"

#add here the technologies and tools you use
tools:
  - "Ruby"
  - "Ruby on Rails"
  - "SQLite"
  - "PostgreSQL"
  - "Bootstrap"
  - "Tailwind"

introduction: "Write something nice about yourself or whatever you want. This text should appear right below your tools."

social_username:
  twitter-x: "twitter-x-username"
  linkedin:  "linkedin-username"
  email:     "username or only example@gmail.com"
  github:    "github-username"

social_link:
  twitter-x: "https://x.com"
  linkedin:  "https://www.linkedin.com"
  github:    "https://github.com"
  email:     example@gmail.com
#--------------------------------------------------------------------

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
